import { FinancialTransactionDetail, FinancialTransactionsResult } from "@app/models/auto-generated";

const transactions = new FinancialTransactionsResult();
transactions.sumBankAccountAmount = 100;
transactions.financialTransactionDetails = [
    {
        financialTransactionId: 508813,
        description: "something",
        entryDateFormattedString: "",
        paidDateFormattedString:"",
        transactionReference: "",
        bankAccountAmount: 25,
        cfcBankAccountId: 10,
        entryType: "DB",
        entryDate: new Date("2018-02-23T00:00:00"),
        transactionType: "MISC",
        financialLedgerId: 228,
        binderId: null,
        binderYear: null,
        sectionId: null,
        lloydsRiskCode: null,
        claimId: null,
        paidDate: new Date("2018-02-22T00:00:00"),
        tags: null,
        notes: null,
        reverseFinancialTransactionId: null,
        addedOn: new Date("2018-05-08T10:59:13.08"),
        addedByContactId: null,
        ledgerReference: "CH000000a",
        binderReference: null,
        binderDescription: null,
        sectionDescription: null,
        binderYearNo: null,
        claimReference: null,
        policyId: null,
        insuredCompanyName: null,
        originalAmountCurrencyId: 1,
        originalAmountCurrencyName: "EUR",
        originalAmountCurrencyIsoCode: "EUR",
        originalAmount: 25,
        sectionShortCode: "asd",
        bankAccountName: "CFCUNTG-EURA",
        bankAccountType: "Loss Fund",
        bankAccountCurrencyId: 1,
        bankAccountCurrencyName: "EUR",
        bankAccountCurrencyIsoCode: "EUR",
        ecfReconciliationId : null,
        carrier: "Lloyds",
        marketType: "marketType",
        outstandingFundId: 0,
        totalAccountAmount: 25,
        tpaFee: false,
        transferredToOffice: false
    },
    {
        financialTransactionId: 508813,
        description: "something",
        entryDateFormattedString: "",
        paidDateFormattedString: "",
        transactionReference: "",
        bankAccountAmount: 25,
        cfcBankAccountId: 10,
        entryType: "DB",
        entryDate: new Date("2018-02-23T00:00:00"),
        transactionType: "MISC",
        financialLedgerId: 228,
        binderId: null,
        binderYear: null,
        sectionId: null,
        lloydsRiskCode: null,
        claimId: null,
        paidDate: new Date("2018-02-22T00:00:00"),
        tags: null,
        notes: null,
        reverseFinancialTransactionId: null,
        addedOn: new Date("2018-05-08T10:59:13.08"),
        addedByContactId: null,
        ledgerReference: "CH000000a",
        binderReference: null,
        binderDescription: null,
        sectionDescription: null,
        binderYearNo: null,
        claimReference: null,
        policyId: null,
        insuredCompanyName: null,
        originalAmountCurrencyId: 1,
        originalAmountCurrencyName: "EUR",
        originalAmountCurrencyIsoCode: "EUR",
        originalAmount: 25,
        sectionShortCode: "asd",
        bankAccountName: "CFCUNTG-EURA",
        bankAccountType: "Loss Fund",
        bankAccountCurrencyId: 1,
        bankAccountCurrencyName: "EUR",
        bankAccountCurrencyIsoCode: "EUR",
        ecfReconciliationId : null,
        carrier: "Lloyds",
        marketType: "marketType",
        outstandingFundId: 0,
        totalAccountAmount: 25,
        tpaFee: false,
        transferredToOffice: false
    },
    {
        financialTransactionId: 508813,
        transactionReference: "",
        description: "something",
        entryDateFormattedString: "",
        paidDateFormattedString: "",
        bankAccountAmount: 25,
        cfcBankAccountId: 10,
        entryType: "DB",
        entryDate: new Date("2018-02-23T00:00:00"),
        transactionType: "MISC",
        financialLedgerId: 228,
        binderId: null,
        binderYear: null,
        sectionId: null,
        lloydsRiskCode: null,
        claimId: null,
        paidDate: new Date("2018-02-22T00:00:00"),
        tags: null,
        notes: null,
        reverseFinancialTransactionId: null,
        addedOn: new Date("2018-05-08T10:59:13.08"),
        addedByContactId: null,
        ledgerReference: "CH000000a",
        binderReference: null,
        binderDescription: null,
        sectionDescription: null,
        binderYearNo: null,
        claimReference: null,
        policyId: null,
        insuredCompanyName: null,
        originalAmountCurrencyId: 1,
        originalAmountCurrencyName: "EUR",
        originalAmountCurrencyIsoCode: "EUR",
        originalAmount: 25,
        sectionShortCode: "asd",
        bankAccountName: "CFCUNTG-EURA",
        bankAccountType: "Loss Fund",
        bankAccountCurrencyId: 2,
        bankAccountCurrencyName: "EUR",
        bankAccountCurrencyIsoCode: "EUR",
        ecfReconciliationId : null,
        carrier: "Lloyds",
        marketType: "marketType",
        outstandingFundId: 0,
        totalAccountAmount: 25,
        tpaFee: false,
        transferredToOffice: false
    },
    {
        financialTransactionId: 508813,
        transactionReference: "",
        description: "something",
        entryDateFormattedString: "",
        paidDateFormattedString: "",
        bankAccountAmount: 25,
        cfcBankAccountId: 1,
        entryType: "DB",
        entryDate: new Date("2018-02-23T00:00:00"),
        transactionType: "MISC",
        financialLedgerId: 228,
        binderId: null,
        binderYear: null,
        sectionId: null,
        lloydsRiskCode: null,
        claimId: null,
        paidDate: new Date("2018-02-22T00:00:00"),
        tags: null,
        notes: null,
        reverseFinancialTransactionId: null,
        addedOn: new Date("2018-05-08T10:59:13.08"),
        addedByContactId: null,
        ledgerReference: "CH000000a",
        binderReference: null,
        binderDescription: null,
        sectionDescription: null,
        binderYearNo: null,
        claimReference: null,
        policyId: null,
        insuredCompanyName: null,
        originalAmountCurrencyId: 1,
        originalAmountCurrencyName: "EUR",
        originalAmountCurrencyIsoCode: "EUR",
        originalAmount: 25,
        sectionShortCode: "asd",
        bankAccountName: "CFCUIRTA-AUDC",
        bankAccountType: "Premiums",
        bankAccountCurrencyId: 5,
        bankAccountCurrencyName: "AUD",
        bankAccountCurrencyIsoCode: "AUD",
        ecfReconciliationId : null,
        carrier: "Lloyds",
        marketType: "marketType",
        outstandingFundId: 0,
        totalAccountAmount: 25,
        tpaFee: false,
        transferredToOffice: true
    }
];
export const TRANSACTIONS = transactions;
