export const TRANSACTIONS: any = {
    SumAccountAmount: 11978.98,
    FinancialTransactionDetails: [
        {
            FinancialTransactionId: 508813,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-02-23T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 22/02/2018 ",
            AccountAmount: 8.1,
            OrigAmountCurrencyId: 1,
            OrigAmount: 8.1,
            PaidDate: "2018-02-22T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 512462,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-03-09T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 08/03/2018 ",
            AccountAmount: 13.76,
            OrigAmountCurrencyId: 1,
            OrigAmount: 13.76,
            PaidDate: "2018-03-08T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 512465,
            CfcBankAccountId: 10,
            EntryType: "CR",
            EntryDate: "2018-03-09T00:00:00",
            TransactionType: "LF",
            FinancialLedgerId: 317,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "PROFESSIONS 16 ",
            AccountAmount: -8800,
            OrigAmountCurrencyId: 1,
            OrigAmount: -8800,
            PaidDate: "2018-03-09T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "UF164810f",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 514381,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-03-20T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 230,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "GROSS INTEREST ",
            AccountAmount: 236.9,
            OrigAmountCurrencyId: 1,
            OrigAmount: 236.9,
            PaidDate: "2018-03-19T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "IN000000c",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 514384,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-03-20T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 230,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "GROSS INTEREST ",
            AccountAmount: 3.68,
            OrigAmountCurrencyId: 1,
            OrigAmount: 3.68,
            PaidDate: "2018-03-19T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "IN000000c",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 514391,
            CfcBankAccountId: 15,
            EntryType: "CR",
            EntryDate: "2018-03-20T00:00:00",
            TransactionType: "CC",
            FinancialLedgerId: 241,
            BinderId: 93,
            BinderYear: "d",
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: 4825,
            Reference: "C004PSE02162625",
            AccountAmount: -2394,
            OrigAmountCurrencyId: 1,
            OrigAmount: -2394,
            PaidDate: "2018-03-20T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.007",
            AddedByContactId: null,
            LedgerReference: "BA076470d",
            BinderReference: "B0309BA076470d",
            BinderDescription: "Combined GL",
            SectionDescription: null,
            BinderYearNo: 2014,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: "C004PSE02162625",
            PolicyId: 162625,
            InsuredCompanyName: "Driver & Labour Recruit Ltd t/a Oak Recruitment",
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 514588,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-03-21T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 20/03/2018 ",
            AccountAmount: 5.81,
            OrigAmountCurrencyId: 1,
            OrigAmount: 5.81,
            PaidDate: "2018-03-20T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 514768,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-03-21T00:00:00",
            TransactionType: "CC",
            FinancialLedgerId: 314,
            BinderId: 61,
            BinderYear: "c",
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: 2772,
            Reference: "C001PSD01104144",
            AccountAmount: 49154.76,
            OrigAmountCurrencyId: 1,
            OrigAmount: 49154.76,
            PaidDate: "2018-03-21T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.007",
            AddedByContactId: null,
            LedgerReference: "UC134810c",
            BinderReference: "B1115U134810",
            BinderDescription: "Professions",
            SectionDescription: null,
            BinderYearNo: 2013,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: "C001PSD01104144",
            PolicyId: 104144,
            InsuredCompanyName: "John Sugars & Partners",
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 514770,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-03-21T00:00:00",
            TransactionType: "CC",
            FinancialLedgerId: 241,
            BinderId: 93,
            BinderYear: "d",
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: 4825,
            Reference: "C004PSE02162625",
            AccountAmount: 2394,
            OrigAmountCurrencyId: 1,
            OrigAmount: 2394,
            PaidDate: "2018-03-21T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.007",
            AddedByContactId: null,
            LedgerReference: "BA076470d",
            BinderReference: "B0309BA076470d",
            BinderDescription: "Combined GL",
            SectionDescription: null,
            BinderYearNo: 2014,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: "C004PSE02162625",
            PolicyId: 162625,
            InsuredCompanyName: "Driver & Labour Recruit Ltd t/a Oak Recruitment",
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 514846,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-03-22T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 21/03/2018 ",
            AccountAmount: 18.73,
            OrigAmountCurrencyId: 1,
            OrigAmount: 18.73,
            PaidDate: "2018-03-21T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 515635,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-03-26T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 23/03/2018 ",
            AccountAmount: 5.86,
            OrigAmountCurrencyId: 1,
            OrigAmount: 5.86,
            PaidDate: "2018-03-23T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 516177,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-03-27T00:00:00",
            TransactionType: "LF",
            FinancialLedgerId: 425,
            BinderId: 110,
            BinderYear: "e",
            SectionId: 261,
            LloydsRiskCode: null,
            ClaimId: 4333,
            Reference: "C001PSE02192098",
            AccountAmount: 19378,
            OrigAmountCurrencyId: 1,
            OrigAmount: 19378,
            PaidDate: "2018-03-27T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.007",
            AddedByContactId: null,
            LedgerReference: "SD150000e",
            BinderReference: "B0618FB15A846A",
            BinderDescription: "ProSurance",
            SectionDescription: "ROW ex US exp",
            BinderYearNo: 2015,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: "C001PSE02192098",
            PolicyId: 192098,
            InsuredCompanyName: "IN2 Engineering Design Partnership or IN2 Design Partnership Ltd or IN2 Engineering Ltd",
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 516307,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-03-28T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 27/03/2018 ",
            AccountAmount: 8.18,
            OrigAmountCurrencyId: 1,
            OrigAmount: 8.18,
            PaidDate: "2018-03-27T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 517584,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-03-29T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 29/03/2018 ",
            AccountAmount: 5.85,
            OrigAmountCurrencyId: 1,
            OrigAmount: 5.85,
            PaidDate: "2018-03-29T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 519164,
            CfcBankAccountId: 15,
            EntryType: "CR",
            EntryDate: "2018-04-11T00:00:00",
            TransactionType: "CC",
            FinancialLedgerId: 323,
            BinderId: 51,
            BinderYear: "b",
            SectionId: 118,
            LloydsRiskCode: null,
            ClaimId: 2111,
            Reference: "C001PSC02062514",
            AccountAmount: -7261.98,
            OrigAmountCurrencyId: 1,
            OrigAmount: -7261.98,
            PaidDate: "2018-04-11T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.007",
            AddedByContactId: null,
            LedgerReference: "BA083580b",
            BinderReference: "B0309BA083580B",
            BinderDescription: "Property",
            SectionDescription: "All",
            BinderYearNo: 2012,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: "C001PSC02062514",
            PolicyId: 62514,
            InsuredCompanyName: "Pharmeng PE Global Ltd Locum Express Medical Ltd Pharmeng Ltd (United Kingdom)",
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 519690,
            CfcBankAccountId: 15,
            EntryType: "CR",
            EntryDate: "2018-04-13T00:00:00",
            TransactionType: "CC",
            FinancialLedgerId: 229,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "PRO D 15 (FEB18",
            AccountAmount: -44000,
            OrigAmountCurrencyId: 1,
            OrigAmount: -44000,
            PaidDate: "2018-04-13T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "IA000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 519691,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-04-13T00:00:00",
            TransactionType: "CC",
            FinancialLedgerId: 229,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "PRO D 15 (FEB18",
            AccountAmount: 44000,
            OrigAmountCurrencyId: 1,
            OrigAmount: 44000,
            PaidDate: "2018-04-13T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "IA000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 519692,
            CfcBankAccountId: 10,
            EntryType: "CR",
            EntryDate: "2018-04-13T00:00:00",
            TransactionType: "LF",
            FinancialLedgerId: 425,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "PRO D 15 (FEB18",
            AccountAmount: -44000,
            OrigAmountCurrencyId: 1,
            OrigAmount: -44000,
            PaidDate: "2018-04-13T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "SD150000e",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 519693,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-04-13T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 12/04/2018 ",
            AccountAmount: 8.21,
            OrigAmountCurrencyId: 1,
            OrigAmount: 8.21,
            PaidDate: "2018-04-12T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 520742,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-04-18T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 17/04/2018 ",
            AccountAmount: 11.82,
            OrigAmountCurrencyId: 1,
            OrigAmount: 11.82,
            PaidDate: "2018-04-17T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 521174,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-04-20T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 230,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "GROSS INTEREST ",
            AccountAmount: 424.97,
            OrigAmountCurrencyId: 1,
            OrigAmount: 424.97,
            PaidDate: "2018-04-19T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "IN000000c",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 521175,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-04-20T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 230,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "GROSS INTEREST ",
            AccountAmount: 13.49,
            OrigAmountCurrencyId: 1,
            OrigAmount: 13.49,
            PaidDate: "2018-04-19T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "IN000000c",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 522193,
            CfcBankAccountId: 15,
            EntryType: "DB",
            EntryDate: "2018-04-24T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 23/04/2018 ",
            AccountAmount: 8.17,
            OrigAmountCurrencyId: 1,
            OrigAmount: 8.17,
            PaidDate: "2018-04-23T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUND-EURA",
            AcctType: "Non Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 538678,
            CfcBankAccountId: 10,
            EntryType: "CR",
            EntryDate: "2018-04-27T00:00:00",
            TransactionType: "LF",
            FinancialLedgerId: 423,
            BinderId: 65,
            BinderYear: "c",
            SectionId: 140,
            LloydsRiskCode: null,
            ClaimId: 1660,
            Reference: "C001PSC00073651",
            AccountAmount: -5999.31,
            OrigAmountCurrencyId: 1,
            OrigAmount: -5999.31,
            PaidDate: "2018-04-27T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.007",
            AddedByContactId: null,
            LedgerReference: "SD130000c",
            BinderReference: "B1115NCPI13108663",
            BinderDescription: "ProSurance",
            SectionDescription: "ROW ex US exp",
            BinderYearNo: 2013,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: "C001PSC00073651",
            PolicyId: 73651,
            InsuredCompanyName: "An Tuath Ghlas",
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 539129,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-04-30T00:00:00",
            TransactionType: "LF",
            FinancialLedgerId: 425,
            BinderId: 110,
            BinderYear: "e",
            SectionId: 261,
            LloydsRiskCode: null,
            ClaimId: 3435,
            Reference: "C001RIIPNGC96035",
            AccountAmount: 2716,
            OrigAmountCurrencyId: 1,
            OrigAmount: 2716,
            PaidDate: "2018-04-30T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.007",
            AddedByContactId: null,
            LedgerReference: "SD150000e",
            BinderReference: "B0618FB15A846A",
            BinderDescription: "ProSurance",
            SectionDescription: "ROW ex US exp",
            BinderYearNo: 2015,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: "C001RIIPNGC96035",
            PolicyId: 147845,
            InsuredCompanyName: "Loic Dehaye Architects ltd.",
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 539287,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-04-30T00:00:00",
            TransactionType: "LF",
            FinancialLedgerId: 423,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "PRO D 13 (JAN18",
            AccountAmount: 5999.31,
            OrigAmountCurrencyId: 1,
            OrigAmount: 5999.31,
            PaidDate: "2018-04-30T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "SD130000c",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        },
        {
            FinancialTransactionId: 539290,
            CfcBankAccountId: 10,
            EntryType: "DB",
            EntryDate: "2018-04-30T00:00:00",
            TransactionType: "MISC",
            FinancialLedgerId: 228,
            BinderId: null,
            BinderYear: null,
            SectionId: null,
            LloydsRiskCode: null,
            ClaimId: null,
            Reference: "CLM 27/04/2018 ",
            AccountAmount: 18.67,
            OrigAmountCurrencyId: 1,
            OrigAmount: 18.67,
            PaidDate: "2018-04-27T00:00:00",
            Tags: null,
            Notes: null,
            ReverseFinancialTransactionId: null,
            AddedOn: "2018-05-08T10:59:13.08",
            AddedByContactId: null,
            LedgerReference: "CH000000a",
            BinderReference: null,
            BinderDescription: null,
            SectionDescription: null,
            BinderYearNo: null,
            BankAccount: "CFCUNTG-EURA",
            AcctType: "Loss Fund",
            AccCurrencyId: 1,
            AccCurrencyName: "EUR",
            ClaimReference: null,
            PolicyId: null,
            InsuredCompanyName: null,
            OrigCurrencyName: "EUR"
        }
    ]
};
