import * as Models from "@app/models/";
import { CommissionInformation } from "@app/quote/models/pricing/CommissionInformation";
import { PricingInformation } from "@app/quote/models/pricing/PricingInformation";
import { InsuranceBasis } from "@app/enums";
import { PropertyLimit } from '@app/quote/models/property-limit.model';
import { PropertyLimitFloatingValues } from '@app/quote/models/property-limit-floating-values.model';

export class Quote {
    public shouldRemoveUnapprovedSubjectivities: boolean;
    public needsPricingRecalculation: boolean;
    public error: Models.SaveQuoteError;
    public gst: number;
    public triaPremium: number;
    public insuranceType: string;
    public insuranceBasis: InsuranceBasis;
    public draftQuoteId: string;
    public quoteReference: number;
    public client: Models.Client;
    public brokerTeam: Models.BrokerTeam;
    public brokerContact: Models.BrokerContact;
    public brokerGroup: Models.BrokerGroup;
    public insuranceTypeId: number;
    public assignedContactId: number;
    public clientLocationId: number;
    public currencyId: number;
    public address: string;
    public quoteDate: Date;
    public inceptionDate: Date;
    public policyPeriod: number;
    public expiryDate: Date;
    public languageId: number;
    public enquiryId: number;
    public enquiryUid: string;
    public expiringPolicyNumber: string;
    public createdByUnderwriter: string;
    public quoteType: string;
    public propSignedDate: Date;
    public product: Models.Product;
    public assignedContact: Models.CfcContact;
    public clientLocation: Models.ClientLocation;
    public currency: Models.Currency;
    public insuredLocation: Models.ClientLocation;
    public commissionInformation: CommissionInformation;
    public wordingVersionId: number;
    public excessWordingVersionId: number;
    public nerdVersion: number;
    public premium: number;
    public taxRate: number;
    public totalDue: number;
    public descriptionOfBusiness: string;
    public isApproved: boolean;
    public policyNumber: string;
    public isPublished: boolean;
    public isBindable: boolean;
    public isEditable: boolean;
    public surplusLineBroker: Models.SurplusLine;
    public state: Models.QuoteState;
    public localBroker: Models.BrokerTeam;
    public binderValidationCriteria: { [key: string]: Models.BinderValidationCriteria; };
    public activities: Models.ActivityDetail[];
    public additionalInsureds: Models.AdditionalInsured[];
    public lossPayees: Models.LossPayee[];
    public subjectivities: Models.QuoteSubjectivity[];
    public coverages: Models.Coverage[];
    public endorsements: Models.Document[];
    public autoAttachedEndorsements: Models.Document[];
    public removedAutoAttachEndorsements: number[];
    public riskQuestionAnswers: Models.RiskQuestionAnswer[];
    public defaultSubjectivities: Models.Subjectivity[];
    public removedDefaultSubjectivities: number[];
    public removedAutoAttachedSubjectivities: string[];
    public pricingInformation: PricingInformation[];
    public pricingGroups: Models.PublishQuotePricingGroup[];
    public taxes: Models.TaxDetails[];
    public bespokeClauses: Models.QuoteBespokeClause[];
    public reAutoSelectAllCoverages: boolean;
    public quoteUid: string;
    public name: string;
    public origin: string;
    public propertyLimits: PropertyLimit[];
    public blastZoneReferenceId?: string;
    public propertyLimitFloatingValues?: PropertyLimitFloatingValues;
    public firstLossLimitValue?: number;
    public hasBlastZoneReservation?: boolean;
    public isAugmented: boolean = false;
    public totalNumberOfRiskQuestions?: number;
    public numberOfRiskQuestionAnswersEnriched?: number;
}
