namespace Hero.Models.Enums;

public enum BuildingUseTypes
{
    COMMERCIAL,
    INDUSTRIAL,
    RESIDENTIAL,
    COMMERCIAL_RESIDENTIAL,
    COUNCIL_GOVERNMENT_BUILDING,
    EMBASSY_CONSULATE,
    ENTERTAINMENT_LEISURE_VENUE,
    FACILITY_ENGAGED_RESEARCH_TESTING_ANIMALS,
    HOTEL,
    ICONIC_BUILDINGS_LANDMARKS,
    MILTARY_PREMISES,
    NUCLEAR_INSTALLATION,
    PLACE_RELIGIOUS_SIGNIFICANCE,
    STADIUM,
    TOURIST_ATTRACTIONS,
    TRANSPORTATION_LINK,
    OTHER
}