/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{html,ts}"],
	prefix: "tw-",
	corePlugins: {
		preflight: false,
        fontFamily: false,
	},
	theme: {
		extend: {
			colors: {
				"cfc-navy-blue": "#01416D",
				"cfc-bright-blue": "#149BD7",
				"cfc-light-blue": "#6DC5E1",
                "cfc-primary-blue": "#0083BD",
				"cfc-green": "#A8EC00",
				"cfc-yellow": "#FFC800",
				"cfc-orange": "#FF7300",
				"cfc-red": "#D81159",
                "cfc-validation-error-red": "#A70D2F",
				"cfc-information-blue": "#EAF9FF",
				"cfc-information-blue-shadow": "#DBEFF7",
				"cfc-mauve": "#A87FFF",
				"cfc-grey": "#575756",
				"cfc-black": "#002b48",
				"cfc-white": "#fff",
				"warning-color": "#ff7300",
				"error-color": "#D81159",
				"hero-light-grey": "#dadada",
				"hero-grey": "#4a4a4a",
                "hero-grey-50": "#F7F9FC",
				"hero-grey-57": "rgba(74, 74, 74, 0.57)",
				"hero-grey-200": "#eeeeee",
				"hero-grey-300": "#F2F2F2",
				"hero-medium-grey": "#9b9c9d",
				"hero-error-warning": "#a12027",
				"hero-link-color": "#149BD7",
				"hero-link-hover-color": "#0c6db0",
				"hero-modal-white": "#FFF",
				"hero-field-color": "#333333",
				"neutral-90": "#F6F9FC",
				"neutral-100": "#F9FAFB",
				"alert-green": "#7BC20D",
                "alert-error": "#D81135",
				"alert-border-green": "#658D0A",
                "alert-border-error": "#910B24",
			},
			fontSize: {
				"font-base-size": "14px",
				"font-size-large": "18px",
				"font-size-small": "12px",
				"font-size-h1": "36px",
				"font-size-h2": "30px",
				"font-size-h3": "24px",
				"font-size-h4": "18px",
				"font-size-h5": "14px",
				"font-size-h6": "12px",
				"font-size-header": "26px",
				"font-size-footer": "20px",
			},
			inset: {},
		},
	},
	plugins: [],
};
